function loadLanguage(lang) {
    $('.lang').each(function (index, element) {
        $(this).text(languages[lang][$(this).attr('key')]);
    })
    $('.activitiesTimeline').attr("src", languages[lang].timeline);
    $('#name').attr("placeholder", languages[lang].name);
    $('#email').attr("placeholder", languages[lang].email);
    $('#phone').attr("placeholder", languages[lang].phone);
    $('#message').attr("placeholder", languages[lang].message);
}

const languages = {
    en: {
        //NAVIGATION
        'history': 'history',
        'information': 'information',
        'activities': 'activities ',
        'organisation': 'organisation',
        'interested': 'interested?',
        'photos': 'pictures',
        'newsfeed': 'newsfeed',
        'contact': 'contact ',
        //HISTORY
        'brief-history': 'A BRIEF HISTORY',
        'brief-history-sub': 'A brief history of where this tradition comes from.',
        'humble': 'Our Humble Beginnings',
        'timeline-1': 'On a certain day in 1919, a man called Karel Fransman received a little book from a friend, called ‘Ground rules of the Baden-Powell Belgian Boy Scouts’. He was really fascinated by the concepts of Scouting and what big differences it could make in the lives of the boys in Ninove. With the help of the local church, represented by father Corteville, the Boy Scouts of Ninove were born in 1920. It was the humble beginning of a success story.',
        '75-years': '75 Years Scouting Ninove',
        'timeline-2': 'In 1994, the Boy Scouts from Ninove blew out 75 candles and they didn’t want to celebrate this anniversary alone. They decided to organize an international camp in their hometown and invited groups from six different countries. To obtain a balanced mix of different nationalities, the Boy and Girl Scouts from Ninove were the only Belgian groups present. Eventually, about 260 Scouts took part, coming from various countries like the Netherlands, Scotland, the Czech Republic, Germany and Italy! All activities on this international camp were built around one theme: Recycling. A ‘Greenteam’ acted as a role model for all participants to use materials in a sustainable and correct way. A sequel to this great success was inevitable…',
        '90-years': '90 Years Scouting Ninove',
        'timeline-3': 'This sequel came in 2010, the year when the Boy Scouts of Ninove turned 90, which was the perfect occasion for a second edition of the Jamborette. Scouting groups from all over the world came to Ninove, where the grasslands at the Wolfsput were transformed into a vibrant Scouting metropolis from the 24th of June until the 2nd of August 2010. The central theme of this camp became ‘Scouting in the middle ages’ and everything referred as much as possible to this time period. Also this second edition turned out to be very successful. About 300 Scouts from 16 different countries attended this event, for the Boy and Girl Scouts from Ninove this tasted for more…',
        '100-years': '100 Years Scouting Ninove',
        'timeline-4': 'In 2020, Scouting in Ninove will celebrate its 100th anniversary. This is the perfect occasion for us to organize a third edition of our Jamborette. Because our centenary really is something special and calls for a good party, this time it will be a festive edition focused on celebrating holidays. We hope to welcome you all as a participant or visitor of the ‘open tent day’ on July 25th 2020.',
        //INFORMATION
        'when': 'When?',
        'when-sub': 'The Jamborette takes place from Saturday the 18th until Tuesday the 28th of July 2020.',
        'what': 'What?',
        'what-sub': 'You will not be bored out during this camp! We have provided various activities such as games, shows, a big dinner etc. Also we will arrange visits to some of Belgium’s most beautiful cities.',
        'where': 'Where?',
        'where-sub': 'Our third Jamborette will take place in the beautiful city of Ninove, also called the oldest, the wildest and the wisest of all cities. Ninove is located in the heart of three pleasant regions. (Scheldeland, Flemish Ardennes and the region we call “The Green Belt”).',
        'ninove': 'Ninove is centrally located in Belgium, so it’s not so far to cities like:',
        'aalst': 'Aalst (15 km)',
        'gent': 'Gent (35 km)',
        'brussel': 'Brussels (20 km)',
        'antwerpen': 'Antwerp (70 km)',
        'cities-sub': 'Our city lies on the banks of the Dender. This river arises in Aalst and ends after 65 km in the Scheldt in Dendermonde.',
        'who': 'Who?',
        'who-sub': 'The Jamborette is meant for boys and girls from the age of 14 (born in 2006 and later) until 18, accompanied by their leaders of course.',
        //ACTIVITIES
        'activities-sub': 'A small overview of some of the many awesome activities that will take place during the Jamborette.',
        'timeline': 'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': 'In this section, you can find the different committees and their heads, who work together with only one objective: making Jamborette 2020 an unforgettable experience!\n' +
            'Questions? Interested? We are only one mail away!\n',
        'program': 'Program',
        'logistics': 'Logistics',
        'security': 'Security',
        'social-media': 'Social Media',
        'kitchen': 'Kitchen',
        'events': 'Events',
        //INTERESTED
        'interested-sub': 'Please do not hesitate to contact us if you are interested in attending the camp or if you have any questions. We are happy to provide you more information!',
        'pricing': 'Pricing',
        'pricing-sub': 'The price for the camp is based on your country of origin and we try to compensate as much as possible for expensive plane tickets. For this, we use a similar system like the Jamboree-team. Our goal is to offer everybody a chance to experience this unforgettable journey! We cannot provide specific information about the price yet, because we are still making contacts with partners and planning activities. However, we can already provide you with an estimated price of € 250. For non-EU citizens, who already spend a lot of money on a plane ticket, we have arranged following contribution:',
        'plane-ticket': 'Plane ticket price',
        'campprice': 'Camp price',
        'benefit': '*To benefit from this contribution, the cheapest plane ticket has to be purchased',
        'registration': 'Registration',
        //PICTURES
        'pictures': 'Pictures',
        'photo-1994': 'Due to the fact that 1994 is a long time ago, \n' +
            'finding pictures is not as easy as we thought it would be. \n' +
            'But remember, a scout never gives up!\n',
        'photo-2010': '',
        'photo-2020': 'Here you\'ll find the first pictures of our jambo 2020. \n' +
            'Soon!\n',
        'close-gallery': 'Close Gallery',
        //NEWSFEED
        'newsfeed-sub': 'Stay tuned with the latest updates concerning our event.\n',
        'paper': 'Jamborette 2020 in the newspaper',
        'who-coming': 'Who\'s coming?',
        //CONTACT
        'contact-us': 'CONTACT US',
        'contact-sub': 'FEEL FREE TO CONTACT US IF YOU HAVE ANY QUESTIONS AT ALL!\n',
        'name': 'Your Name *',
        'phone': 'Your Email *',
        'email': 'Your Phone *',
        'message': 'Your Message *',
        'send-message': 'Send message',
    },
    de: {
        'history': 'GESCHICHTE',
        'information': 'INFORMATION',
        'activities': 'AKTIVITÄTEN ',
        'organisation': 'ORGANISATION',
        'interested': 'INTERESSIERT?',
        'photos': 'FOTO’S',
        'newsfeed': 'Nachrichtenüberblick',
        'contact': 'KONTAKT ',
        //HISTORY
        'brief-history': 'EINE KURZE GESCHICHTE',
        'brief-history-sub': 'Eine kurze uber die Tradition',
        'humble': 'Unsere bescheidenen Anfänge',
        'timeline-1': 'An einem bestimmten Tag im Jahre 1919, erhielt ein Mann namens Karel Fransman von einem Freund das kleines Büchlein „Grundregeln der Baden-Powell Belgian Boy Scouts“. Er war wirklich fasziniert von den Konzepten des Scouting und davon, welche großen Unterschiede es für die Leben der Jungen von Ninove machen könnte. Mit Hilfe der örtlichen Kirche, vertreten durch Vater Corteville, wurden die Scouts von Ninove 1920 geboren. Es war der Bescheidene Beginn einer Erfolgsgeschichte.',
        '75-years': '75 Jahre Scouting in Ninove',
        'timeline-2': '1994 bliesen die Boy Scouts von Ninove 75 Kerzen aus, und sie wollten diesen Jahrestag nicht allein feiern. Sie beschlossen, ein internationales Camp in ihrer Heimatstadt zu organisieren und luden aus sechs verschiedenen Länder ein. Für eine ausgewogene Mischung verschiedener Nationalitäten waren nur die Boy und Girl Scouts von Ninove als einzigen belgische Gruppen anwesend. Schließlich nahmen etwa 260 Scouts aus verschiedenen Ländern wie den Niederlanden, Schottland, der Tschechischen Republik, Deutschland und Italien teil! Alle Aktivitäten während des Camps beschäftigten sich mit einem Thema: Recycling. Ein „Greenteam“ fungierte als Vorbild für alle Teilnehmer, um Materialien auf eine nachhaltige und korrekte Weise einzusetzen. Eine Fortsetzung dieses großen Erfolgs war unvermeidlich…',
        '90-years': '90 Jahre Scouting in Ninove',
        'timeline-3': 'Die Fortsetzung kam 2010. Dem Jahr, in dem die Boy Scouts von Ninove 90 Jahre alt wurden - der perfekte Anlass für eine zweite Edition des Jamborette. Scouting Gruppen aus aller Welt kamen nach Ninove, wo das Weideland von Wolfsput von24. Juni bis zum 2. August 2010 in eine pulsierende Scouting Metropole verwandelt wurde. Das zentrale Thema dieses Camps wurde „Scouting in the middle ages – Scouting im Mittelalter“ und alles bezog sich, so gut wie möglich, auf dieses Zeitalter. Auch die zweite Edition stellte sich als sehr erfolgreich heraus. Etwa 300 Scouts aus 16 verschiedene Ländern nahmen an diesem Ereignis teil. Für die Boy und Girl Scouts von Ninove schmeckte das nach mehr…',
        '100-years': '100 Jahre Scouting in Ninove',
        'timeline-4': '2020 feiert Scouting in Ninove den 100. Jahrestag. Dies ist die perfekte Gelegenheit für und, eine dritte Edition unseres Jamborette zu organisieren. Da unser Jubiläum wirklich etwas Besonderes ist und nach einer Party verlangt, wird es diesmal eine festliche Veranstaltung sein, bei der die Feiertage im Mittelpunkt stehen. Wir hoffen, euch alle als Teilnehmer oder Besucher zum „Tag des offenen Zelts“ am 25. Juli 2020 begrüßen zu dürfen.',
        //INFORMATION
        'when': 'Wann?',
        'when-sub': 'Das Jamborette findet von Samstag, den 18. Juli 2020 bis Dienstag den 28. Juli 2020 statt.',
        'what': 'Was?',
        'what-sub': 'Ihr werdet euch während des Camps nicht langweilen. Wir werden verschiedene Aktivitäten wie Spiele, Shows, ein großes Abendessen etc. anbieten. Außerdem werden wir Besuche von einigen der schönsten Städte Belgiens organisieren.',
        'where': 'Wo?',
        'where-sub': 'Wie bereits die beiden vorherigen Editionen, wird das dritte Jamborette ebenfalls in unserer schönen Stadt Ninove stattfinden - inmitten der drei wunderschönen Regionen Scheldeland, Flämische Ardennen und der Region, die wir den „Grünen Gürtel“ nennen.',
        'ninove': 'Ninove liegt im Zentrum Belgiens, also ist es nicht sehr weit entfernt von Städten, wie:',
        'aalst': 'Aalst (15 km)',
        'gent': 'Gent (35 km)',
        'brussel': 'Brüssel (20 km)',
        'antwerpen': 'Antwerpen (70 km)',
        'cities-sub': 'Unsere Stadt liegt an den Ufern des Flusses Dender, die in Ath entspringt und nach 65 km in Dendermonde in die Schlede mündet.',
        'who': 'Für wen?',
        'who-sub': 'Das Jamborette ist gedacht für Jungen und Mädchen von 14 bis 18 Jahren – natürlich begleitet durch ihre Gruppenleiter.',
        //ACTIVITIES
        'activities-sub': 'Ein kleines Übersicht von alle tolle Aktivitäten während das Jamborette.',
        'timeline': 'img/timeline/timeline-de.png',
        //ORGANISATION
        'organisation-sub': 'In diese Sektion finden Sie die verschiedene Komitees und ihr Haupt, Sie arbeiten zusammen mit nur ein ziel: Jamborette 2020 ein unvergeßliche Erfahrung!\n Fragen? Interessiert? Wir sind nur eine Email entfernt!\n',
        'communication': 'Kommunikation',
        'program': 'Programm',
        'logistics': 'Logistik',
        'security': 'Sicherheit',
        'social-media': 'Sozialen Medien',
        'kitchen': 'Küche',
        'events': 'Events',
        //INTERESTED
        'interested-sub': 'Zögert nicht, Kontakt mit uns aufzunehmen, wenn ihr Interesse oder Fragen habt. Wir freuen uns, euch mehr Informationen zu geben.',
        'pricing': 'Preis?',
        'pricing-sub': 'Der Preis für das Camp ist abhängig von eurem Herkunftsland und wir versuchen so gut wie möglich beim Preis für das Camp entgegen zu kommen, falls ihr teure Flugtickets habt. Dafür nutzen wir ein ähnliches System wie das Jamboree Team. Unser Ziel ist es, jedem eine Chance zu geben, dies unvergessliche Reise zu erleben. Wir können noch keine sichere Auskunft über den endgültigen Preis geben, da wir noch mit der Kontaktaufnahme zu Partnern und mit der Planung von Aktivitäten beschäftigt sind. Dennoch können wir euch schon eine erste Einschätzung von 250 € geben. Für Nicht-EU-Bürger, die bereits eine Menge Geld für Flugtickets ausgeben, haben wir eine Preisstaffelung eingerichtet:',
        'plane-ticket': 'Preis Flugticket',
        'campprice': 'Preis Camp',
        'benefit': 'Um von diese Staffelung profitieren zu können, muss das billigste Flugticket gekauft werden.',
        'registration': 'Anmeldung',
        //PICTURES
        'pictures': 'FOTO’S',
        'photo-1994': 'Bilder finden aus 1994 ist schwieriger als wir gedacht haben. Aber ein Scout verzicht nicht!',
        'photo-2010': '',
        'photo-2020': 'Hier finden Sie die Bilder von unsere Jamborette 2020. Bald.',
        'close-gallery': 'Galerie schließen',
        //NEWSFEED
        'newsfeed-sub': 'Bleiben Sie dran mit die neuesten Entwicklungen.\n',
        'paper': 'Jamborette 2020 in die Zeitung.',
        'who-coming': 'Wer kommt?',
        //CONTACT
        'contact-us': 'KONTAKTIERE UNS',
        'contact-sub': 'KONTAKTIERE UNS FALLS SIE FRAGEN HABEN!\n',
        'name': 'Ihre Name *',
        'phone': 'Ihre Email *',
        'email': 'Ihr Telefon *',
        'message': 'Ihr Bericht *',
        'send-message': 'Bericht schicken',
    },
    es: {
        'history': 'Historia',
        'information': 'Informaciones',
        'activities': 'Actividades',
        'organisation': 'Organización',
        'interested': '¿Interesado?',
        'photos': 'Imágenes',
        'newsfeed': 'Noticias',
        'contact': 'contacto',
        //HISTORY
        'brief-history': 'Una breve historia',
        'brief-history-sub': 'Una breve historia sobre el origen de esta tradición',
        'humble': 'Nuestros humildes comienzos',
        'timeline-1': 'Un cierto día del año 1919, un hombre llamado Karel Fransman recibió de un amigo un pequeño libro llamado "Las reglas básicas de los scouts belgas de Baden-Powell". Estaba realmente fascinado de cómo se podrían hacer diferencias tan grandes en las vidas de los niños en Ninove. Con la ayuda de la iglesia local, Corteville, los scouts de Ninove nacieron en 1920. Fue el comienzo humilde de una historia de éxito.',
        '75-years': '75 años de los scouts de Ninove',
        'timeline-2': 'En 1994, los scouts de Ninove apagaron 75 velas y no querían celebrar este aniversario solo con su grupo. Decidieron organizar un campamento internacional en su ciudad natal e invitaron a grupos de scouts de seis países diferentes. Para obtener una mezcla equilibrada de diferentes nacionalidades, los Scouts de Ninove fueron los únicos grupos belgas presentes. Finalmente, cerca de 260 scouts participaron al campamento. Participaron entre otros scouts de Escocia, de la República Checa, Alemania e Italia. Todas las actividades durante este campamento internacional fueron construidas alrededor de un tema: el reciclaje. Un \'Greenteam\' actuó como un modelo a seguir para que todos los participantes usaran los materiales de una manera sostenible y correcta. Una secuela de este gran éxito fue inevitable ...',
        '90-years': '90 años de los scouts de Ninove',
        'timeline-3': 'Esta secuela se produjo en 2010, cuando los Boy Scouts de Ninove cumplieron 90 años, lo que fue la ocasión perfecta para una segunda edición de la Jamborette. Grupos de Scouting de todo el mundo llegaron a Ninove, donde los pastizales del Wolfsput en Ninove se transformaron en una vibrante metrópolis de ‘Scouting’ desde el 24 de junio hasta el 2 de agosto de 2010. El tema central de este campamento era el "Scouting en la Edad Media". y todo refirió tanto como fuera posible a esta epoca. También esta segunda edición resultó ser muy exitosa. Alrededor de 300 Scouts de 16 países diferentes asistieron a este evento. Los Scouts y guías de Ninove estaban esperando por más…',
        '100-years': '100 años de los scouts de Ninove',
        'timeline-4': 'En 2020, Los scouts y guías de Ninove celebrarán su centenario. Esto claramente es la ocasión perfecta para organizar una tercera edición de nuestra Jamborette. Debido a que nuestro centenario realmente es algo especial y requiere una gran fiesta, esta vez será una edición festiva centrada en la celebración de los días festivos. Esperamos darle la bienvenida como participante, o como visitante del "día de la carpa abierta" que tendrá lugar el 25 de julio de 2020.',
        //INFORMATION
        'when': '¿Cuándo?',
        'when-sub': 'La Jamborette tendrá lugar del sábado 18 al martes 28 de julio de 2020.',
        'what': '¿Qué?',
        'what-sub': '¡No te aburrirás durante este campamento! Hemos brindado diversas actividades como juegos, espectáculos, una gran cena multicultural, etc. También organizaremos visitas a algunas de las ciudades más hermosas de Bélgica.',
        'where': '¿Donde?',
        'where-sub': 'Nuestra tercera Jamborette tendrá lugar en la ciudad de Ninove, que se describe como "el corazón de las tres regiones hermosas de Flandes" (Scheldeland, Ardenas flamencas y la región que llamamos "El Cinturón Verde").',
        'ninove': 'Ninove se encuentra en el centro de Bélgica, así que no se sitúa lejos de ciudades como:',
        'aalst': 'Aalst (15 km)',
        'gent': 'Gante (35 km)',
        'brussel': 'Bruselas (20 km)',
        'antwerpen': 'Amberes (70 km)',
        'cities-sub': 'Nuestra ciudad se encuentra a orillas del rió Dender. Este río surge en Aat y termina 65 km más lejos en el río Scheldt en Dendermonde.',
        'who': '¿Para quién?',
        'who-sub': 'La Jamborette está destinada a niños y niñas de 14 años (nacidos en 2006 y posteriores) a 18 años acompañados por sus líderes, por supuesto.',
        //ACTIVITIES
        'activities-sub': 'En lo que sigue, mencionamos unas de las muchas actividades increíbles que tendrán lugar durante la Jamborette.',
        'timeline': 'img/timeline/timeline-es.png',
        //ORGANISATION
        'organisation-sub': 'En esta sección, puedes encontrar los diferentes comités y sus jefes, que trabajan juntos con un solo objetivo: hacer de la Jamborette 2020 una experiencia inolvidable.\n' +
            ' \n' +
            '¿Preguntas? ¡Contáctanos!\n',
        'communication': 'Comunicación',
        'program': 'Programación',
        'logistics': 'Logística',
        'security': 'Seguridad',
        'social-media': 'Redes sociales',
        'kitchen': 'Cocina',
        'events': 'Eventos',
        //INTERESTED
        'interested-sub': 'No dude en ponerse en contacto con nosotros si estáis interesados o si tenéis alguna duda o pregunta. ¡Estamos encantados de darles más información!',
        'pricing': 'Precios',
        'pricing-sub': 'El precio del campamento se basa en vuestro país de origen. Tratamos de compensar lo más posible los billetes de avión caros. Para esto, usamos un sistema similar como el equipo de Jamboree. ¡Nuestro objetivo es ofrecer a todos la oportunidad de experimentar este viaje inolvidable!\n' +
            'Todavía no podemos proporcionar información concreta sobre el precio, ya que todavía estamos poniéndonos en contacto con los socios y estamos organizando las actividades. Sin embargo, ya podemos estimar el precio al €250. Para los ciudadanos que no pertenecen a la UE, que han gastado mucho dinero en un boleto de avión, prevemos una contribución:\n',
        'plane-ticket': 'Precio billete de avión',
        'campprice': 'precio campamento',
        'benefit': '* Para beneficiarse de esta contribución, se debe comprar el boleto de avión más barato.',
        'registration': 'Matriculación',
        //PICTURES
        'pictures': 'Imágenes',
        'photo-1994': 'Debido al hecho de que 1994 es hace mucho tiempo,\n' +
            'Encontrar imágenes no es tan fácil como pensábamos.\n' +
            'Pero recuerda, ¡un explorador nunca se rinde!\n',
        'photo-2010': '',
        'photo-2020': 'Aquí podrías encontrar unas fotos muy pronto.\n',
        'close-gallery': 'cierra la galeria',
        //NEWSFEED
        'newsfeed-sub': 'Estén atentos con las últimas actualizaciones sobre nuestro evento.',
        'paper': 'Jamborette 2020 en el periódico',
        'who-coming': '¿Quién está viniendo?',
        //CONTACT
        'contact-us': 'Contacto',
        'contact-sub': ' ¡Siéntate libre de contactarnos si tienes alguna pregunta!',
        'name': 'Nombre',
        'phone': 'Número de teléfono',
        'email': 'Correo electrónico',
        'message': 'Mensaje',
        'send-message': 'Enviar mensaje',
    },
    fr: {
        'history': 'HISTOIRE',
        'information': 'L’INFORMATION',
        'activities': 'ACTIVITéS',
        'organisation': 'L’ORGANISATION',
        'interested': 'INTERESSÉ?',
        'photos': 'PHOTOS',
        'newsfeed': 'NEWSFEED',
        'contact': 'CONTACT',
        //HISTORY
        'brief-history': 'UN BREF HISTORIQUE',
        'brief-history-sub': 'Un bref historique de notre naissance et tradition. ',
        'humble': 'Nos modestes débuts',
        'timeline-1': 'En 1919, un jeune homme Karel Fransman a reçu un livre comme cadeau d’un ami : “Règles fondamentales des Scouts Baden-Powell de Belgique”.\n' +
            'Il était fasciné par l’idée des Scouts. Quelle différence peut faire l’idée de Scouts sur les jeunes de Ninove ? \n' +
            'À l’aide du prêtre Corteville, les Scouts de Ninove sont nés en 1920. \n' +
            'Un modeste début d’un succès.',
        '75-years': '75 ans de Scouting Ninove',
        'timeline-2': 'En 1994, les Scouts de Ninove fêtaient leur 75ime anniversaire. \n' +
            'Ils ne voulaient pas fêter cette occasion spéciale tout seul ! Donc, ils ont décidé d’organiser un camp mondial avec des scouts de six différents pays. Pour garantir un certain équilibre entre les participants, les scouts de Ninove étaient le seul groupe belge.\n' +
            'Au total, il y avait 260 participants de différents pays comme : les Pays-Bas, l’Écosse, la Republique Tchèque, l’Allemagne et l’Italie.\n' +
            'Le thème centrale était : le recyclage ! Un ‘Green team’ donnait des conseils aux participants pour utiliser des matériaux durables pendant le camp. \n' +
            'Après cette réussite, la suite était inévitable.',
        '90-years': '90 ans de Scouting Ninove',
        'timeline-3': 'La suite venait en 2010. Pour leur 90ème anniversaire, une deuxième édition du Jamborette était parfaite comme célébration ! \n' +
            'Des Scouts du monde entier nous ont rejoint à Ninove, qui pendant dix jours devenait une métropole pour des Scouts. \n' +
            'Nous avons choisi comme thème centrale : Scouting pendant le Moyen Age. La deuxième édition à été un grand succès ! Environ 300 Scouts de 16 différents pays ont participé. Le compte à rebours déjà commençait…',
        '100-years': '100 ans de Scouting Ninove',
        'timeline-4': 'En 2020, Scouting à Ninove va fêter leur centenaire. L’événement idéal pour organiser une troisième édition du  Jamborette. Un centenaire mérite d’être fêté d’une façon spéciale. Nous célébrons un mix de nos meilleures jours fériés. Nous espérons de vous accueillir ; comme participant ou visiteur de notre porte ouverte, le 25 Juillet 2020.',
        //INFORMATION
        'when': 'Quand ?',
        'when-sub': 'Le Jamborette 2020 aura lieu du 28 juillet au 8 août 2020 à Ninove. ',
        'what': 'Quoi ? ',
        'what-sub': 'Il n’y a pas de place pour l’ennui pendant Jamborette 2020. Nous préparons beaucoup et diverses activités, par exemple : des jeux de groupe, des spectacles, un souper en groupe… \n' +
            'Nous planifions aussi des voyages aux plus belles villes de Belgique.',
        'where': 'Où ? ',
        'where-sub': 'La troisième édition du Jamborette aura lieu à Ninove : une ville accueillante au centre de Belgique. ',
        'ninove': 'À proximité de Ninove, vous trouverez des villes comme : ',
        'aalst': 'Alost (15 km)',
        'gent': 'Gand (35 km)',
        'brussel': 'Bruxelles (20 km)',
        'antwerpen': 'Anvers (70 km) ',
        'cities-sub': 'Ninove se trouve au bord de la Dendre. La rivière prend sa source à Ath et se jette dans l’Escaut à Termonde.',
        'who': 'Pour qui ? ',
        'who-sub': 'Le Jamborette s’adresse aux garçons et filles, à partir de 14 ans (né en 2006) au 18 ans et leurs chefs.',
        //ACTIVITIES
        'activities-sub': 'Un petit aperçu de quelques-unes des nombreuses activités géniales qui auront lieu pendant le Jamborette.',
        'timeline': 'img/timeline/timeline-fr.png',
        //ORGANISATION
        'organisation-sub': 'Dans cette section, vous trouverez les différents comités et leurs chefs, qui collaborent ensemble à une cause : que le Jamborette soit de nouveau un véritable succès. Questions ? Contactez-nous par mail. ',
        'communication': 'Communication',
        'program': 'Programme',
        'logistics': 'Logistique',
        'security': 'Sécurité',
        'social-media': 'Social Media',
        'kitchen': 'Restauration',
        'events': 'Événements',
        //INTERESTED
        'interested-sub': 'N’hésitez pas de nous contacter ! Nous sommes à votre entière disposition pour vous donner plus d’info. ',
        'pricing': 'Le prix ?',
        'pricing-sub': 'Le prix du camp se fonde sur son pays d’origine. Le but étant que tout le monde nous peut rejoindre au Jamborette. \n' +
            'Nous ne pouvons pas encore donner des informations concrètes sur le prix, car nous sommes toujours occupés à établir des contacts et à planifier des activités, bien évidemment. Néanmoins, nous pouvons déjà annoncer que le prix indicatif est de €250. Pour les non-européens qui paient déjà un montant élevé pour le billet d\'avion, nous proposons une intervention:',
        'plane-ticket': 'Prix de billet d’avion',
        'campprice': 'Prix de camp',
        'benefit': '*Afin de pouvoir utiliser cette intervention, le billet d\'avion réservé doit logiquement être le moins cher.',
        'registration': 'L’enregistrement',
        //PICTURES
        'pictures': 'PHOTOS',
        'photo-1994': 'En raison du fait que 1994 a eu lieu il y a longtemps,\n' +
            'trouver des images n’est pas aussi facile que nous le pensions.\n' +
            'Mais rappelez-vous, de souvenirs des scouts ne s’oublient jamais!\n',
        'photo-2010': '',
        'photo-2020': 'Vous trouverez ici les premières images de notre Jambo 2020, bientôt!',
        'close-gallery': 'fermer la galerie',
        //NEWSFEED
        'newsfeed-sub': 'Restez à l\'affût des dernières mises à jour concernant notre événement.',
        'paper': 'Jamborette 2020 dans le journal',
        'who-coming': 'Qui vient?',
        //CONTACT
        'contact-us': 'CONTACT',
        'contact-sub': 'N’hésitez pas à nous contacter pour toute information complémentaire. ',
        'name': 'Votre nom',
        'phone': 'Votre numéro de téléphone',
        'email': 'Votre adresse e-mail',
        'message': 'Votre message',
        'send-message': 'Envoyez message',
    },
    it: {
        'history': 'STORIA',
        'information': 'INFORMAZIONE',
        'activities': 'ATTIVITÀ ',
        'organisation': 'L’ORGANIZZAZIONNE',
        'interested': 'INTERESSATO?',
        'photos': 'IMMAGINI',
        'newsfeed': 'NOTIZIE',
        'contact': 'contact ',
        //HISTORY
        'brief-history': 'UNA BREVE STORIA',
        'brief-history-sub': 'Una breve storia della provenienza di questa tradizione',
        'humble': 'La nostra nascita modesta',
        'timeline-1': 'Un giorno nell’anno 1919, un certo Karel Fransman ha ricevuto un libretto di un amico con le regole fondamentali di Baden-Powell Belgian Boy Scouts. Era affascinato dai principi di Scautismo e cosa questi potrebbero significare per i ragazzi di Ninove. Con l’aiuto della parrocchia locale (E.H.Corteville), Scouts Ninove viene nato nel 1920. Era una nascita modesta con un grande successo.',
        '75-years': '75 anni Scouts Ninove',
        'timeline-2': 'Nel 1994 Scouts Ninove ha celebrato il suo settantacinquesimo anniversario e non volevano celebrare da solo. Per questo hanno deciso di organizzare un campo mondiale per la prima volta, nella loro propria città, Ninove! Volevano la partecipazione di circa sei Paesi, Scouts Ninove era il solo gruppo belga pur di rimanere l’equilibrio. Alla fine quasi 260 esploratori di vari Paesi hanno partecipato al campo! Tra le varie nazionalità c’erano italiani, scozzesi, cechi, tedeschi e olandesi.Tutte le attività di quel campo avevano un tema: Recycling. C’era un ‘Greenteam’ che aveva come compito di insegnare agli altri come dovevano essere più sostenibile e come dovevano riciclare. Il campo era un grande successo, quindi hanno organizzato una seconda edizione.',
        '90-years': '90 anni Scouts Ninove',
        'timeline-3': 'La seconda edizione era nel 2010, quell’anno ‘Scouts Ninove’ esisteva per 90 anni. Per quella ragione hanno organizzato di nuovo un altro ‘jamborette’. Gruppi di scoutismo di tutto il mondo erano andato a Ninove da 24 giungo a 2 luglio. Ninove era trasformato in un metropoli vivace per lo scoutismo.  Anche per questo campo c’era un tema: Scouting in the Middle Ages. Il campo e le attività si riferivano a quel periodo. Il terreno era diviso in vari piccoli accampamenti con nomi che riferivano a diversi figuri medioevali (per esempio: Campo Robin Hood, Maria la Sanguinaria e Re Artù). Questa seconda edizione era di nuovo un grande successo e alla fine 300 esploratori di 16 diversi nazionalità hanno partecipato a quest’esperienza indimenticabile! Dopo il successo di quell’edizione, Scouts Ninove voleva organizzare di nuovo un altro ‘jamborette’. ',
        '100-years': '100 anni Scouts Ninove',
        'timeline-4': 'Nel 2020 Scouts Ninove festeggia la sua centenaria esistenza, in una parola: l’occasione perfetta per organizzare una terza edizione. Quindi abbiamo avuto l’idea per festeggiare questa svolta nella nostra storia con un campo mondiale (Jamborette). Quest’anno il tema è ‘giorni festivi’. Ogni giorno il terreno verrà decorato in un giorno festivo, per es. San Valentino o il carnevale di Ninove. Inoltre vogliamo invitare, i cittadini di Ninove alla nostra giornata di visita che ha luogo il 25 luglio 2020.',
        //INFORMATION
        'when': 'Quando?',
        'when-sub': 'Jamborette 2020 aver luogo da 18 a 28 luglio 2020.',
        'what': 'Che?',
        'what-sub': 'Jamborette non è un campo normale. I partecipanti non avranno tempo per annoiarsi. Questi dieci giorni sono riempiti da tante attività moderne ma con rispetto per le leggi vecchi del Scautismo. Grandi giochi con tutti i partecipanti, una cena gigantesca con centinaia esploratori ed esploratrici, una cerimonia di apertura e chiusura. Vogliamo presentarvi con tutto quello che Ninove e Belgio può offrire. Lo facciamo anche tramite gite alle più belle città di Belgio!',
        'where': 'Dove?',
        'where-sub': 'Per la terza edizione del nostro campo mondiale (Jamborette 2020), abbiamo trovato una locazione bellissima vicino al centro di Ninove. Ninove è una città pittoresca accanto alle rive della Dendre/Dender.',
        'ninove': 'Ninove è vicino a qualche città bellissima ed interessante:',
        'aalst': 'Aalst (15 km)',
        'gent': 'Ghent (35 km)',
        'brussel': 'Bruxelles (20 km)',
        'antwerpen': 'Anversa (70 km)',
        'cities-sub': '',
        'who': 'Chi?',
        'who-sub': 'Jamborette 2020 organizza un campo per esploratori ed esploratrici da quattordici anni a diciotto anni, accompagnato dai loro capi (ovviamente).',
        //ACTIVITIES
        'activities-sub': 'Qui si trova qualche esempio di attività che succederanno durante il Jamborette.',
        'timeline': 'img/timeline/timeline-it.png',
        //ORGANISATION
        'organisation-sub': 'Qui può trovare la nostra amministrazione ambiziosa. Siamo sempre pronti per rispondere a tutte le vostre domande.',
        'communication': 'Communication',
        'program': 'Programma',
        'logistics': 'Logistica',
        'security': 'Protezione',
        'social-media': 'Social Media',
        'kitchen': 'Cucina',
        'events': 'Eventi',
        //INTERESTED
        'interested-sub': 'Non esitate a contattarci se siete interessati in nostro campo o se avete domande. Siamo pronti di fornirvi più informazioni.',
        'pricing': 'Prezzo',
        'pricing-sub': 'È più difficile determinare un prezzo fisso per il campo perché siamo ancora occupati con progettare le attività. Ma il prezzo indicativo per questo campo è €250 per persona. Per incoraggiare la partecipazione di gruppi non europei, vogliamo fare un’intervenzione secondo le seguenti regole:',
        'plane-ticket': 'Prezzo biglietto aereo	',
        'campprice': 'Prezzo del campo',
        'benefit': '*Per profittare di questa intervenzione è necessario prenotare i biglietti più economici.',
        'registration': 'Registrazione',
        //PICTURES
        'pictures': 'IMMAGINI',
        'photo-1994': 'Non siamo riusciti a trovare immagini del campo di 1994 dato che è passato un po’ di tempo. Nonostante questo piccolo ostacolo, continuiamo a cercare!',
        'photo-2010': '',
        'photo-2020': "Qui si troverà le foto di Jamborette 2020.",
        'close-gallery': 'Chiudi la galleria',
        //NEWSFEED
        'newsfeed-sub': 'Qui si trova le notizie del nostro evento.',
        'paper': 'Jamborette 2020 nel giornale',
        'who-coming': 'Chi viene all’evento?',
        //CONTACT
        'contact-us': 'CONTATTACI',
        'contact-sub': 'Non esita a contattaci per chiedere qualcosa!\n',
        'name': 'Il tuo nome *',
        'phone': 'Il tuo numero di telefono *',
        'email': 'La tua e-mail *',
        'message': 'Il tuo messaggio *',
        'send-message': 'Invia il tuo messaggio',
    },
    nl: {
        'history': 'Geschiedenis',
        'information': 'Informatie',
        'activities': 'Activiteiten',
        'organisation': 'organisatie',
        'interested': 'Interesse?',
        'photos': 'FOTO’S',
        'newsfeed': 'Nieuwsoverzicht',
        'contact': 'contact ',
        //HISTORY
        'brief-history': 'EEN KORTE GESCHIEDENIS',
        'brief-history-sub': 'Een kort overzicht hoe deze traditie is ontstaan.',
        'humble': 'Ons bescheiden ontstaan',
        'timeline-1': 'Op een zekere dag in het jaar 1919, kreeg een zekere Karel Fransman van een vriend een klein boekje met daarin de grondregels van de Baden-Powell Belgian Boy Scouts. Hij was enorm gefascineerd door de concepten van scouting en wat deze zouden kunnen betekenen voor de jongens in Ninove. Met de hulp van de lokale parochie, meerbepaald E.H. Corteville, werden de Scouts van Ninove geboren in 1920. Het was een bescheiden ontstaan van wat later een succesverhaal zou blijken.',
        '75-years': '75 jaar Scouts Ninove',
        'timeline-2': 'In het jaar 1994 blies de Scouts van Ninove 75 kaarsjes uit, en dat wilden ze liever niet alleen vieren. Daarom besloten ze voor het eerst een wereldkamp te organiseren, en dat in hun eigen thuisstad! Er werd gemikt op de deelname van een zestal landen, met Ninove als enige Belgische scouts- en gidsengroep, om het evenwicht tussen de verschillende nationaliteiten te bewaren. Uiteindelijk namen er een 260-tal scoutsleden van diverse landen deel aan het kamp! Onder de verschillende nationaliteiten bevonden er zich onder andere Nederlanders, Schotten, Tsjechen, Duitsers en Italianen. Het werd ook niet ‘zomaar’ een wereldkamp, want alle activiteiten stonden in het teken van een thema, namelijk ‘recycling’. Zo was er onder meer zelfs een volledig ‘Greenteam’ aanwezig met een voorbeeldfunctie voor alle andere kampgangers om correct en duurzaam met alle materiaal om te gaan. Het kamp werd een groot succes, en zou nog een vervolg kennen…',
        '90-years': '90 jaar Scouts Ninove',
        'timeline-3': 'En dat vervolg kwam er in 2010! Dat jaar bestond Scouts Ninove 90 jaar. Om deze reden werd er opnieuw een jamborette georganiseerd. Scoutsgroepen van over de hele wereld zakten af naar Ninove, waar de weiden aan de Wolfsput van 24 juni tot 2 juli 2010 werden omgetoverd tot een bruisende scoutsmetropool. Ook voor dit kamp was er opnieuw een thema uitgewerkt, namelijk ‘scouting in the middle ages’. Het kamp en de activiteiten refereerden dan ook zoveel mogelijk naar de middeleeuwen. Zo kregen de verschillende subkampen een naam verwijzend naar spraakmakende figuren uit de geschiedenis (zo waren er bijvoorbeeld Kamp Robin Hood, Bloody Mary en King Arthur).  Deze tweede editie was opnieuw een groot succes en uiteindelijk namen ongeveer 300 scoutsleden van 16 verschillende nationaliteiten deel aan deze onvergetelijke ervaring! En opnieuw smaakte dit voor de scoutsleiding van Ninove naar meer…',
        '100-years': '100 jaar Scouts Ninove',
        'timeline-4': 'In 2020 zullen de scouts van Ninove hun honderdjarig bestaan vieren, met andere woorden: de perfecte gelegenheid om dit feest groots aan te pakken en een derde Jamborette te organiseren. Een honderdjarig bestaan betekent ‘Feest’, dus hoe kunnen we deze speciale mijlpaal in de (Ninoofse) scoutsgeschiedenis beter vieren dan het organiseren van een wereldkamp met als thema ‘Feestdagen’. Iedere dag wordt het kampterrein dan ook omgetoverd in het decor van een specifieke feestdag, van Valentijn tot het échte Ninoofse carnaval, alles komt aan bod. Verder willen we jullie, als bezoeker, Nienovieter of sympathisant, alvast uitnodigen op onze Opententendag die plaatsvindt op 25 juli 2020.',
        //INFORMATION
        'when': 'Wanneer?',
        'when-sub': 'Jamborette 2020 zal doorgaan van zaterdag 18 tot dinsdag 28 juli 2020.',
        'what': 'Wat?',
        'what-sub': 'Jamborette is niet zomaar een kamp. De deelnemers zullen alvast geen tijd hebben om zich te vervelen tijdens onze tiendaagse. We vullen deze tien dagen met een hele waaier aan activiteiten, met een moderne toets, maar steeds met respect voor de aloude scoutswetten. Grote spelen met alle deelnemers, een gigantisch diner met honderden scouts, een heuse openings- en slotshow; we laten niets aan het toeval over en entertainen onze buitenlandse gasten met het beste van Ninove én België. Verder laten we onze deelnemers kennismaken met het mooiste wat ons land te bieden heeft door uitstappen naar de mooiste Belgische steden!',
        'where': 'Waar?',
        'where-sub': 'Voor de derde editie van ons wereldkamp, Jamborette 2020, vonden we een prachtige locatie vlakbij  het centrum van onze gezellige thuishaven, Ninove. Een provinciestad met karakter, langs de oevers van de Dender. ',
        'ninove': 'Ninove is erg centraal gelegen;  in de buurt van enkele interessante en mooie steden:',
        'aalst': 'Aalst (15km)',
        'gent': 'Gent (35 km)',
        'brussel': 'Brussel (20 km)',
        'antwerpen': 'Antwerpen (70 km)',
        'cities-sub': '',
        'who': 'Wie?',
        'who-sub': 'Jamborette 2020 verwelkomt graag jongens en meisjes van 14 tot 18 jaar oud, uiteraard vergezeld door hun leiders.',
        //ACTIVITIES
        'activities-sub': 'Een kort overzicht van enkele van de activiteiten die van deze Jamborette een unieke ervaring zullen maken.',
        'timeline': 'img/timeline/timeline-nl.png',
        //ORGANISATION
        'organisation-sub': 'Hier kan u het ambitieuze team vinden dat zijn schouders onder het grootste Jamborette 2020-project zet. We zijn steeds bereikbaar voor al uw vragen!',
        'communication': 'Communicatie',
        'program': 'Programma',
        'logistics': 'Logistiek',
        'security': 'Veiligheid',
        'social-media': 'Social Media',
        'kitchen': 'Kookploeg',
        'events': 'Evenementen',
        //INTERESTED
        'interested-sub': 'Aarzel niet om ons te contacteren bij vragen of interesse; onze organisatie is steeds bereikbaar om meer informatie te geven.',
        'pricing': 'Prijs?',
        'pricing-sub': 'Het is erg moeilijk om nu reeds een concrete kostprijs voor het kamp mee te delen, aangezien wij als organisatie nog volop bezig zijn met het leggen van contacten en plannen van activiteiten,... Wat we wel al kunnen vertellen is dat de richtprijs voorlopig €250 bedraagt. Voor niet-Europeanen die reeds een hoog bedrag betalen voor het vliegtuigticket, voorzien wij een tussenkomst:',
        'plane-ticket': 'Prijs vliegtuigticket',
        'campprice': 'Prijs kamp',
        'benefit': '*Om van deze tussenkomst gebruik te kunnen maken, moet  uiteraard het goedkoopste vliegticket worden geboekt.',
        'registration': 'Registratie',
        //PICTURES
        'pictures': "Foto's",
        'photo-1994': 'Aangezien 1994 al even geleden is, is het niet zo eenvoudig als gedacht om digitale afbeeldingen te vinden. Maar een echt scout geeft nooit op!',
        'photo-2010': '',
        'photo-2020': 'Binnenkort kunt u hier de eerste foto’s van de jambo 2020 vinden!',
        'close-gallery': 'Gallerij sluiten',
        //NEWSFEED
        'newsfeed-sub': 'Volg alle laatste ontwikkelingen in verband met ons evenement.\n',
        'paper': 'Jamborette 2020 in de krant',
        'who-coming': 'Wie komt er al?',
        //CONTACT
        'contact-us': 'Contacteer ons',
        'contact-sub': 'AARZEL NIET OM ONS TE CONTACTEREN IN HET GEVAL VAN VRAGEN!\n',
        'name': 'Jouw naam *',
        'phone': 'Jouw telefoonnummer *',
        'email': 'Jouw email *',
        'message': 'Jouw bericht *',
        'send-message': 'Bericht versturen',
    },
    no: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'photos': '',
        'newsfeed': '',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline': 'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'name': '',
        'phone': '',
        'email': '',
        'message': '',
        'send-message': '',
    },
};

