function loadLanguage(lang) {
    $('.lang').each(function (index, element) {
        $(this).text(languages[lang][$(this).attr('key')]);
    })
    $('.activitiesTimeline').attr("src",languages[lang].timeline)
}

const languages = {
    en: {
        //NAVIGATION
        'history': 'history',
        'information': 'information',
        'activities': 'activities ',
        'organisation': 'organisation',
        'interested': 'interested?',
        'photos': 'pictures',
        'newsfeed': 'newsfeed',
        'contact': 'contact ',
        //HISTORY
        'brief-history': 'A BRIEF HISTORY',
        'brief-history-sub': 'A brief history of where this tradition comes from.',
        'humble': 'Our Humble Beginnings',
        'timeline-1': 'On a certain day in 1919, a man called Karel Fransman received a little book from a friend, called ‘Ground rules of the Baden-Powell Belgian Boy Scouts’. He was really fascinated by the concepts of Scouting and what big differences it could make in the lives of the boys in Ninove. With the help of the local church, represented by father Corteville, the Boy Scouts of Ninove were born in 1920. It was the humble beginning of a success story.',
        '75-years': '75 Years Scouting Ninove',
        'timeline-2': 'In 1994, the Boy Scouts from Ninove blew out 75 candles and they didn’t want to celebrate this anniversary alone. They decided to organize an international camp in their hometown and invited groups from six different countries. To obtain a balanced mix of different nationalities, the Boy and Girl Scouts from Ninove were the only Belgian groups present. Eventually, about 260 Scouts took part, coming from various countries like the Netherlands, Scotland, the Czech Republic, Germany and Italy! All activities on this international camp were built around one theme: Recycling. A ‘Greenteam’ acted as a role model for all participants to use materials in a sustainable and correct way. A sequel to this great success was inevitable…',
        '90-years': '90 Years Scouting Ninove',
        'timeline-3': 'This sequel came in 2010, the year when the Boy Scouts of Ninove turned 90, which was the perfect occasion for a second edition of the Jamborette. Scouting groups from all over the world came to Ninove, where the grasslands at the Wolfsput were transformed into a vibrant Scouting metropolis from the 24th of June until the 2nd of August 2010. The central theme of this camp became ‘Scouting in the middle ages’ and everything referred as much as possible to this time period. Also this second edition turned out to be very successful. About 300 Scouts from 16 different countries attended this event, for the Boy and Girl Scouts from Ninove this tasted for more…',
        '100-years': '100 Years Scouting Ninove',
        'timeline-4': 'In 2020, Scouting in Ninove will celebrate its 100th anniversary. This is the perfect occasion for us to organize a third edition of our Jamborette. Because our centenary really is something special and calls for a good party, this time it will be a festive edition focused on celebrating holidays. We hope to welcome you all as a participant or visitor of the ‘open tent day’ on July 25th 2020.',
        //INFORMATION
        'when': 'When?',
        'when-sub': 'The Jamborette takes place from Saturday the 18th until Tuesday the 28th of July 2020.',
        'what': 'What?',
        'what-sub': 'You will not be bored out during this camp! We have provided various activities such as games, shows, a big dinner etc. Also we will arrange visits to some of Belgium’s most beautiful cities.',
        'where': 'Where?',
        'where-sub': 'Our third Jamborette will take place in the beautiful city of Ninove, also called the oldest, the wildest and the wisest of all cities. Ninove is located in the heart of three pleasant regions. (Scheldeland, Flemish Ardennes and the region we call “The Green Belt”).',
        'ninove': 'Ninove is centrally located in Belgium, so it’s not so far to cities like:',
        'aalst': 'Aalst (15 km)',
        'gent': 'Gent (35 km)',
        'brussel': 'Brussels (20 km)',
        'antwerpen': 'Antwerp (70 km)',
        'cities-sub': 'Our city lies on the banks of the Dender. This river arises in Aalst and ends after 65 km in the Scheldt in Dendermonde.',
        'who': 'Who?',
        'who-sub': 'The Jamborette is meant for boys and girls from the age of 14 (born in 2006 and later) until 18, accompanied by their leaders of course.',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
    de: {
        'history': 'GESCHICHTE',
        'information': 'INFORMATION',
        'activities': 'AKTIVITÄTEN ',
        'organisation': 'ORGANISATION',
        'interested': 'INTERESSIERT?',
        'photos': 'FOTO’S',
        'newsfeed': 'Nachrichtenüberblick',
        'contact': 'KONTAKT ',
        //HISTORY
        'brief-history':'EINE KURZE GESCHICHTE',
        'brief-history-sub':'Eine kurze uber die Tradition',
        'humble':'Unsere bescheidenen Anfänge',
        'timeline-1':'An einem bestimmten Tag im Jahre 1919, erhielt ein Mann namens Karel Fransman von einem Freund das kleines Büchlein „Grundregeln der Baden-Powell Belgian Boy Scouts“. Er war wirklich fasziniert von den Konzepten des Scouting und davon, welche großen Unterschiede es für die Leben der Jungen von Ninove machen könnte. Mit Hilfe der örtlichen Kirche, vertreten durch Vater Corteville, wurden die Scouts von Ninove 1920 geboren. Es war der Bescheidene Beginn einer Erfolgsgeschichte.',
        '75-years':'75 Jahre Scouting in Ninove',
        'timeline-2':'1994 bliesen die Boy Scouts von Ninove 75 Kerzen aus, und sie wollten diesen Jahrestag nicht allein feiern. Sie beschlossen, ein internationales Camp in ihrer Heimatstadt zu organisieren und luden aus sechs verschiedenen Länder ein. Für eine ausgewogene Mischung verschiedener Nationalitäten waren nur die Boy und Girl Scouts von Ninove als einzigen belgische Gruppen anwesend. Schließlich nahmen etwa 260 Scouts aus verschiedenen Ländern wie den Niederlanden, Schottland, der Tschechischen Republik, Deutschland und Italien teil! Alle Aktivitäten während des Camps beschäftigten sich mit einem Thema: Recycling. Ein „Greenteam“ fungierte als Vorbild für alle Teilnehmer, um Materialien auf eine nachhaltige und korrekte Weise einzusetzen. Eine Fortsetzung dieses großen Erfolgs war unvermeidlich…',
        '90-years':'90 Jahre Scouting in Ninove',
        'timeline-3':'Die Fortsetzung kam 2010. Dem Jahr, in dem die Boy Scouts von Ninove 90 Jahre alt wurden - der perfekte Anlass für eine zweite Edition des Jamborette. Scouting Gruppen aus aller Welt kamen nach Ninove, wo das Weideland von Wolfsput von24. Juni bis zum 2. August 2010 in eine pulsierende Scouting Metropole verwandelt wurde. Das zentrale Thema dieses Camps wurde „Scouting in the middle ages – Scouting im Mittelalter“ und alles bezog sich, so gut wie möglich, auf dieses Zeitalter. Auch die zweite Edition stellte sich als sehr erfolgreich heraus. Etwa 300 Scouts aus 16 verschiedene Ländern nahmen an diesem Ereignis teil. Für die Boy und Girl Scouts von Ninove schmeckte das nach mehr…',
        '100-years':'100 Jahre Scouting in Ninove',
        'timeline-4':'2020 feiert Scouting in Ninove den 100. Jahrestag. Dies ist die perfekte Gelegenheit für und, eine dritte Edition unseres Jamborette zu organisieren. Da unser Jubiläum wirklich etwas Besonderes ist und nach einer Party verlangt, wird es diesmal eine festliche Veranstaltung sein, bei der die Feiertage im Mittelpunkt stehen. Wir hoffen, euch alle als Teilnehmer oder Besucher zum „Tag des offenen Zelts“ am 25. Juli 2020 begrüßen zu dürfen.',
        //INFORMATION
        'when':'Wann?',
        'when-sub':'Das Jamborette findet von Samstag, den 18. Juli 2020 bis Dienstag den 28. Juli 2020 statt.',
        'what':'Was?',
        'what-sub':'Ihr werdet euch während des Camps nicht langweilen. Wir werden verschiedene Aktivitäten wie Spiele, Shows, ein großes Abendessen etc. anbieten. Außerdem werden wir Besuche von einigen der schönsten Städte Belgiens organisieren.',
        'where':'Wo?',
        'where-sub':'Wie bereits die beiden vorherigen Editionen, wird das dritte Jamborette ebenfalls in unserer schönen Stadt Ninove stattfinden - inmitten der drei wunderschönen Regionen Scheldeland, Flämische Ardennen und der Region, die wir den „Grünen Gürtel“ nennen.',
        'ninove':'Ninove liegt im Zentrum Belgiens, also ist es nicht sehr weit entfernt von Städten, wie:',
        'aalst':'Aalst (15 km)',
        'gent':'Gent (35 km)',
        'brussel':'Brüssel (20 km)',
        'antwerpen':'Antwerpen (70 km)',
        'cities-sub':'Unsere Stadt liegt an den Ufern des Flusses Dender, die in Ath entspringt und nach 65 km in Dendermonde in die Schlede mündet.',
        'who':'Für wen?',
        'who-sub':'Das Jamborette ist gedacht für Jungen und Mädchen von 14 bis 18 Jahren – natürlich begleitet durch ihre Gruppenleiter.',
        //ACTIVITIES
        'activities-sub':'Ein kleines Übersicht von alle tolle Aktivitäten während das Jamborette.',
        'timeline':'img/timeline/timeline-de.png',
        //ORGANISATION
        'organisation-sub':'In diese Sektion finden Sie die verschiedene Komitees und ihr Haupt, Sie arbeiten zusammen mit nur ein ziel: Jamborette 2020 ein unvergeßliche Erfahrung! Fragen? Interessiert? Wir sind nur eine Email entfernt!',
        'communication':'Kommunikation',
        'program':'Programm',
        'logistics':'Logistik',
        'security':'Sicherheit',
        'social-media':'Sozialen Medien',
        'kitchen':'Küche',
        'events':'Events',
        //INTERESTED
        'interested-sub':'Zögert nicht, Kontakt mit uns aufzunehmen, wenn ihr Interesse oder Fragen habt. Wir freuen uns, euch mehr Informationen zu geben.',
        'pricing':'Preis?',
        'pricing-sub':'Der Preis für das Camp ist abhängig von eurem Herkunftsland und wir versuchen so gut wie möglich beim Preis für das Camp entgegen zu kommen, falls ihr teure Flugtickets habt. Dafür nutzen wir ein ähnliches System wie das Jamboree Team. Unser Ziel ist es, jedem eine Chance zu geben, dies unvergessliche Reise zu erleben. Wir können noch keine sichere Auskunft über den endgültigen Preis geben, da wir noch mit der Kontaktaufnahme zu Partnern und mit der Planung von Aktivitäten beschäftigt sind. Dennoch können wir euch schon eine erste Einschätzung von 250 € geben. Für Nicht-EU-Bürger, die bereits eine Menge Geld für Flugtickets ausgeben, haben wir eine Preisstaffelung eingerichtet:',
        'plane-ticket':'Preis Flugticket',
        'campprice':'Preis Camp',
        'benefit':'Um von diese Staffelung profitieren zu können, muss das billigste Flugticket gekauft werden.',
        'registration':'Anmeldung',
        //PICTURES
        'pictures':'FOTO’S',
        'photo-1994':'Bilder finden aus 1994 ist schwieriger als wir gedacht haben. Aber ein Scout verzicht nicht!',
        'photo-2010':'',
        'photo-2020':'Hier finden Sie die Bilder von unsere Jamborette 2020. Bald.',
        'close-gallery':'Galerie schließen',
        //NEWSFEED
        'newsfeed-sub':'Bleiben Sie dran mit die neuesten Entwicklungen.',
        'paper':'Jamborette 2020 in die Zeitung.',
        'who-coming':'Wer kommt?',
        //CONTACT
        'contact-us':'KONTAKTIERE UNS',
        'contact-sub':'KONTAKTIERE UNS FALLS SIE FRAGEN HABEN!',
        'send-message':'Bericht schicken',
    },
    es: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'photos': '',
        'newsfeed': '',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
    fr: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'photos': '',
        'newsfeed': '',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
    it: {
        'history': 'STORIA',
        'information': 'INFORMAZIONE',
        'activities': 'ATTIVITÀ ',
        'organisation': 'L’ORGANIZZAZIONNE',
        'interested': 'INTERESSATO?',
        'photos': 'IMMAGINI',
        'newsfeed': 'NOTIZIE',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
    nl: {
        'history': 'Geschiedenis',
        'information': 'Informatie',
        'activities': 'Activiteiten',
        'organisation': 'organisatie',
        'interested': 'Interesse?',
        'photos': 'FOTO’S',
        'newsfeed': 'Nieuwsoverzicht',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
    no: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'photos': '',
        'newsfeed': '',
        'contact': 'contact ',
        //HISTORY
        'brief-history': '',
        'brief-history-sub': '',
        'humble': '',
        'timeline-1': '',
        '75-years': '',
        'timeline-2': '',
        '90-years': '',
        'timeline-3': '',
        '100-years': '',
        'timeline-4': '',
        //INFORMATION
        'when': '',
        'when-sub': '',
        'what': '',
        'what-sub': '',
        'where': '',
        'where-sub': '',
        'ninove': '',
        'aalst': '',
        'gent': '',
        'brussel': '',
        'antwerpen': '',
        'cities-sub': '',
        'who': '',
        'who-sub': '',
        //ACTIVITIES
        'activities-sub': '',
        'timeline':'img/timeline/timeline-en.png',
        //ORGANISATION
        'organisation-sub': '',
        //INTERESTED
        'interested-sub': '',
        'pricing': '',
        'pricing-sub': '',
        'plane-ticket': '',
        'campprice': '',
        'benefit': '',
        'registration': '',
        //PICTURES
        'pictures': '',
        'photo-1994': '',
        'photo-2010': '',
        'photo-2020': '',
        'close-gallery': '',
        //NEWSFEED
        'newsfeed-sub': '',
        'paper': '',
        'who-coming': '',
        //CONTACT
        'contact-us': '',
        'contact-sub': '',
        'send-message': '',
    },
};

