function loadLanguage(lang) {
    $('.lang').each(function (index, element) {
        $(this).text(languages[lang][$(this).attr('key')]);
    })
}

const languages = {
    en: {
        'history': 'history',
        'information': 'information',
        'activities': 'activities ',
        'organisation': 'organisation',
        'interested': 'interested?',
        'pictures': 'pictures',
        'newsfeed': 'newsfeed',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
    de: {
        'history': 'GESCHICHTE',
        'information': 'INFORMATION',
        'activities': 'AKTIVITÄTEN ',
        'organisation': 'ORGANISATION',
        'interested': 'INTERESSIERT?',
        'pictures': 'FOTO’S',
        'newsfeed': 'Nachrichtenüberblick',
        'contact': 'KONTAKT ',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
    es: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'pictures': '',
        'newsfeed': '',
        'contact': '',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
    fr: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'pictures': '',
        'newsfeed': '',
        'contact': '',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
    it: {
        'history': 'STORIA',
        'information': 'INFORMAZIONE',
        'activities': 'ATTIVITÀ ',
        'organisation': 'L’ORGANIZZAZIONNE',
        'interested': 'INTERESSATO?',
        'pictures': 'IMMAGINI',
        'newsfeed': 'NOTIZIE',
        'contact': 'CONTATTACI',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''

    },
    nl: {
        'history': 'Geschiedenis',
        'information': 'Informatie',
        'activities': 'Activiteiten',
        'organisation': 'organisatie',
        'interested': 'Interesse?',
        'pictures': 'FOTO’S',
        'newsfeed': 'Nieuwsoverzicht',
        'contact': 'Contact',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
    no: {
        'history': '',
        'information': '',
        'activities': ' ',
        'organisation': '',
        'interested': '',
        'pictures': '',
        'newsfeed': '',
        'contact': '',
        'contact': 'contact ',
        'brief-history':'',
        'brief-history-sub':'',
        'humble':'',
        'timeline-1':'',
        '75-years':'',
        'timeline-2':'',
        '90-years':'',
        'timeline-3':'',
        '100-years':'',
        'timeline-4':'',
        'when':'',
        'when-sub':'',
        'what':'',
        'what-sub':'',
        'where':'',
        'where-sub':'',
        'ninove':'',
        'aalst':'',
        'gent':'',
        'brussel':'',
        'antwerpen':'',
        'cities-sub':'',
        'who':'',
        'who-sub':'',
        'activities-sub':'',
        'organisation-sub':'',
        'interested-sub':'',
        'pricing':'',
        'pricing-sub':'',
        'plane-ticket':'',
        'campprice':'',
        'benefit':'',
        'registration':'',
        'pictures':'',
        'newsfeed-sub':'',
        'paper':'',
        'who-coming':'',
        'contact-us':'',
        'contact-sub':'',
        'send-message':'',
        'photo-1994':'',
        'photo-2010':'',
        'photo-2020':'',
        'close-gallery':''
    },
};

